name: Dependency Caching CI

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual run for easy testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
